"""Build the site, from the same places the app gets its own answers.

`docs/index.html` carried a comment saying "Generated from auteur/theme.py —
the same palette the app and icons use". Nothing generated it. Measured against
`theme.py`: all thirteen colours it shipped had drifted in both light and dark,
and three roles were missing entirely. The most visible was `--moss`, green on
the site and teal in the app for months — the site was selling a
different-coloured product than the one it linked to.

That is the same failure as the iOS bundle: a file described as generated, with
no generator, quietly going stale because nothing could tell. The fix is the
same. This writes the page, the palette comes from `auteur/theme.py`, the words
come from `auteur/brand.py`, and a test compares what is committed to what this
produces.

    python3 tools/site/build_site.py [out.html]
"""

from __future__ import annotations

import html
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from auteur import brand, pricing, theme  # noqa: E402

OUT = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "docs" / "index.html"

#: Where a person can actually get it. A landing page whose buttons do nothing
#: is worse than one without buttons, so anything not yet real says so rather
#: than linking to a store page that does not exist.
TRY_IT = "https://claude.ai/code/artifact/11666d9b-4b2f-4c15-818b-185262d6cc2a"


def _vars(scheme: str) -> str:
    return "\n".join(
        f"    --{role.replace('_', '-')}: {theme.hex_of(role, scheme)};" for role in theme.ROLES
    )


def _features() -> str:
    out = []
    for feature in brand.FEATURES:
        note = "" if feature.on_device else '<span class="aside">needs a copy you run</span>'
        out.append(
            "      <li>\n"
            f"        <h3>{html.escape(feature.headline)}{note}</h3>\n"
            f"        <p>{html.escape(feature.body)}</p>\n"
            "      </li>"
        )
    return "\n".join(out)


def _plans() -> str:
    """The three tiers, from `auteur/pricing.py`.

    Nothing here is typed twice: the prices are derived from the comparison
    set in that module, and the saving on the top tier is computed from the
    same constant the Stripe coupon carries.
    """
    out = []
    for tier in pricing.TIERS:
        classes = "plan featured" if tier is pricing.TOP_TIER else "plan"
        was = ""
        if tier is pricing.TOP_TIER:
            was = (
                '<p class="was">'
                f"{pricing.TOP_TIER_OFF:.0%} off — "
                f"<s>${tier.dollars:.2f}</s> ${pricing.discounted():.2f}/mo"
                "</p>"
            )
        items = "\n".join(f"          <li>{html.escape(line)}</li>" for line in tier.includes)
        every = "" if not tier.dollars else '<span class="per"> / month</span>'
        out.append(
            f'      <li class="{classes}">\n'
            f"        <h3>{html.escape(tier.name)}</h3>\n"
            f'        <p class="price">{tier.monthly}{every}</p>\n'
            f"        {was}\n"
            f'        <p class="blurb">{html.escape(tier.blurb)}</p>\n'
            "        <ul>\n"
            f"{items}\n"
            "        </ul>\n"
            "      </li>"
        )
    return "\n".join(out)


PAGE = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="color-scheme" content="dark light">
<meta name="theme-color" content="{theme.THEME_COLOR}" media="(prefers-color-scheme: dark)">
<meta name="theme-color" content="{theme.LIGHT_THEME_COLOR}" media="(prefers-color-scheme: light)">
<title>{brand.NAME} — {html.escape(brand.TAGLINE.lower())}</title>
<meta name="description" content="{html.escape(brand.PROMISE)}">
<meta property="og:title" content="{brand.NAME} — {html.escape(brand.TAGLINE)}">
<meta property="og:description" content="{html.escape(brand.PROMISE)}">
<meta property="og:type" content="website">
<style>
  /* Generated by tools/site/build_site.py from auteur/theme.py.
     Do not edit this file: run the builder. The last hand-edited copy drifted
     thirteen colours from the app it was selling. */
  :root {{
    color-scheme: dark light;
{_vars("dark")}
  }}
  @media (prefers-color-scheme: light) {{
    :root {{
{_vars("light")}
    }}
  }}

  * {{ box-sizing: border-box; }}
  html {{ -webkit-text-size-adjust: 100%; }}
  body {{
    margin: 0;
    background: var(--ground);
    color: var(--text);
    font: 17px/1.65 ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI",
          Roboto, sans-serif;
  }}
  main {{ max-width: 760px; margin: 0 auto; padding: max(env(safe-area-inset-top), 56px) 22px 96px; }}
  a {{ color: var(--ember-text); }}

  /* The mark, set in the app's own type rather than an image, so it cannot
     fall out of step with the app the way the palette did. */
  .mark {{
    font-size: clamp(44px, 11vw, 76px);
    letter-spacing: -0.04em;
    font-weight: 600;
    margin: 0;
    line-height: 1;
  }}
  .mark::after {{
    content: "";
    display: inline-block;
    width: 0.36em; height: 0.36em;
    margin-left: 0.1em;
    border-radius: 50%;
    /* The accent, not the error colour. `rust` is documented in theme.py as
       "it did not work, or needs attention" — the app paints a failed sign-in
       and the delete-account button with it. The wordmark is neither. */
    background: var(--ember);
    vertical-align: baseline;
  }}
  .tagline {{ color: var(--text-muted); font-size: clamp(19px, 4.4vw, 23px); margin: 14px 0 0; }}
  .positioning {{ font-size: 19px; margin: 26px 0 0; max-width: 60ch; }}
  .caveat {{ color: var(--text-faint); margin: 14px 0 0; max-width: 60ch; }}

  .actions {{ display: flex; flex-wrap: wrap; gap: 12px; margin: 34px 0 0; }}
  .go {{
    display: inline-flex; align-items: center; min-height: 48px;
    padding: 0 22px; border-radius: 999px; text-decoration: none;
    font-weight: 600; background: var(--ember); color: var(--on-ember);
  }}
  .go.quiet {{ background: transparent; color: var(--text); border: 1px solid var(--line); }}
  .go:focus-visible, a:focus-visible {{ outline: 2px solid var(--ember); outline-offset: 3px; }}

  hr {{ border: 0; border-top: 1px solid var(--line); margin: 64px 0; }}
  h2 {{ font-size: 14px; text-transform: uppercase; letter-spacing: 0.09em;
       color: var(--text-faint); font-weight: 600; margin: 0 0 22px; }}

  ul.features {{ list-style: none; margin: 0; padding: 0; display: grid; gap: 30px; }}
  @media (min-width: 640px) {{ ul.features {{ grid-template-columns: 1fr 1fr; gap: 30px 40px; }} }}
  ul.features h3 {{ font-size: 18px; margin: 0 0 6px; }}
  ul.features p {{ margin: 0; color: var(--text-muted); }}
  .aside {{
    display: inline-block; margin-left: 8px; padding: 2px 8px; border-radius: 999px;
    font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em;
    background: var(--raised); color: var(--text-faint); vertical-align: middle;
  }}

  .stores {{ display: flex; flex-wrap: wrap; gap: 12px; margin: 0; padding: 0; list-style: none; }}
  .stores li {{
    border: 1px solid var(--line); border-radius: 14px; padding: 14px 18px;
    background: var(--surface); color: var(--text-muted); font-size: 15px;
  }}
  .stores strong {{ display: block; color: var(--text); font-size: 16px; }}

  ul.plans {{ list-style: none; margin: 0; padding: 0; display: grid; gap: 18px; }}
  @media (min-width: 720px) {{ ul.plans {{ grid-template-columns: repeat(3, 1fr); }} }}
  .plan {{
    border: 1px solid var(--line); border-radius: 18px; padding: 22px 20px 24px;
    background: var(--surface); display: flex; flex-direction: column; gap: 4px;
  }}
  /* The top tier carries the advertised discount, so it is the one the eye
     should land on. It is marked with the accent as a border rather than as a
     fill: `cream` would need a "text on cream" role that does not exist in
     theme.py, and inventing one here is exactly how this page ended up with a
     hand-copied palette thirteen colours out of date. */
  .plan.featured {{ border-color: var(--ember); box-shadow: inset 0 0 0 1px var(--ember); }}
  .plan h3 {{ font-size: 17px; margin: 0; }}
  .plan .price {{ font-size: 34px; font-weight: 600; letter-spacing: -0.02em; margin: 6px 0 0; }}
  .plan .per {{ font-size: 15px; font-weight: 400; color: var(--text-muted); letter-spacing: 0; }}
  .plan .was {{ margin: 4px 0 0; font-size: 14px; font-weight: 600; color: var(--ember-text); }}
  .plan .was s {{ color: var(--text-faint); font-weight: 400; }}
  .plan .blurb {{ margin: 10px 0 0; color: var(--text-muted); font-size: 15px; }}
  .plan ul {{ list-style: none; margin: 14px 0 0; padding: 0; display: grid; gap: 8px; font-size: 15px; }}
  .plan li {{ padding-left: 20px; position: relative; }}
  .plan li::before {{
    content: ""; position: absolute; left: 2px; top: 0.62em;
    width: 8px; height: 8px; border-radius: 50%; background: var(--moss);
  }}
  .trial {{ font-size: 19px; margin: 0 0 22px; max-width: 60ch; }}
  .smallprint {{ color: var(--text-faint); font-size: 14px; margin: 18px 0 0; max-width: 66ch; }}

  footer {{ margin-top: 70px; color: var(--text-faint); font-size: 15px; }}
  footer a {{ margin-right: 18px; display: inline-block; min-height: 44px; line-height: 44px; }}

  @media (prefers-reduced-motion: no-preference) {{
    .go {{ transition: transform 120ms ease; }}
    .go:active {{ transform: scale(0.97); }}
  }}
</style>
</head>
<body>
<main>
  <h1 class="mark">{brand.NAME}</h1>
  <p class="tagline">{html.escape(brand.TAGLINE)}</p>
  <p class="positioning">{html.escape(brand.POSITIONING)}</p>
  <p class="caveat">{html.escape(brand.CAVEAT)}</p>

  <div class="actions">
    <a class="go" href="{TRY_IT}">Make one in your browser</a>
    <a class="go quiet" href="https://github.com/abucaria-afk/Social-media">Read the code</a>
  </div>

  <hr>

  <h2>What it does</h2>
  <ul class="features">
{_features()}
  </ul>

  <hr>

  <h2>What it costs</h2>
  <p class="trial">{html.escape(pricing.headline())}</p>
  <ul class="plans">
{_plans()}
  </ul>
  <p class="smallprint">Every paid plan starts with {pricing.TRIAL_DAYS} days free and no card
    charged until they are up. Prices are compared against the advertised monthly rate of
    {", ".join(rival.name for rival in pricing.ENTRY_RIVALS)} and
    {", ".join(rival.name for rival in pricing.TOP_RIVALS)}, read {pricing.AS_OF}.
    The browser build stays free: it runs on your device, so it costs us nothing to give you.</p>

  <hr>

  <h2>Where to get it</h2>
  <ul class="stores">
    <li><strong>In a browser</strong>Nothing to install. It cuts on your device.</li>
    <li><strong>iPhone and iPad</strong>Built and not yet submitted.</li>
    <li><strong>Android</strong>Built and not yet submitted.</li>
  </ul>

  <footer>
    <a href="privacy.html">Privacy</a>
    <a href="terms.html">Terms</a>
    <a href="https://github.com/abucaria-afk/Social-media">Source</a>
  </footer>
</main>
</body>
</html>
"""


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(PAGE, encoding="utf-8")
    print(OUT, len(PAGE), "bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
